### ISSUE TITLE
[FEAT] Download game information (specifically lat/lon of locations visited)

### ISSUE THREAD

**Issue by agausmann** [GeoGuess/Geoguess#105]
**Is your feature request related to a problem? Please describe.**

I think it would be cool to keep a history of the places I've "visited" via GeoGuess, so I can go back and visit them again.

**Describe the solution you'd like**

I want to keep a table (probably a CSV) with the datetimes and locations of all of the points across all of my games. I'll manipulate the data myself, but I would like an easy way to get that data from GeoGuess. There's already a "History" button that reads from a "history" key in the browser's local storage and displays the data graphically, and I'd like to have an easy way (via the webpage UI) to dump the data from those games so I can add it to my table.

**Describe alternatives you've considered**

It would be neat if GeoGuess had more extensive history support, like going back and looking at the places in street view again. However, that feature is not related to downloading the raw data, and a major motivation for this feature request is being able to archive the data myself, instead of leaving it in the browser's local storage.

**Comment by BilelJegham** [comment]
You can already replay a game.
![image](https://user-images.githubusercontent.com/20130405/108389633-258d6a00-7210-11eb-8648-f02f41dd63c5.png)

However, you are right, have CSV export for all game points can be great to build the player stats page (#37).

**Comment by BilelJegham** [comment]
Added in the pull request #115

Can you check the csv format ?

[export_2021-02-24T21_37_43.372Z.zip](https://github.com/GeoGuess/Geoguess/files/6038998/export_2021-02-24T21_37_43.372Z.zip)

https://deploy-preview-115--geoguess2.netlify.app/
