### ISSUE TITLE
[FEAT] Flexible number of rounds per game

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/GeoGuess#125]
[https://discord.com/channels/758443244387303435/792739542058532865/816424488471494676](https://discord.com/channels/758443244387303435/792739542058532865/816424488471494676)

**Comment by BilelJegham** [comment]
I see issues with his request. 
With more rounds, games will not have the same maximum score (5000). History sorting will become complex.

**Comment by wlanowski** [comment]
> 
> 
> I see issues with his request.
> With more rounds, games will not have the same maximum score (5000). History sorting will become complex.

Sad story... For me it would be more interesting to have flexible number of rounds, than to have a history with max score... :/

**Comment by BilelJegham** [comment]
If you think, it should be appreciated by players. You can implement it. 

It's not complicated.
You have nbRound variable in StreetView.vue

https://github.com/GeoGuess/Geoguess/blob/dc36c681e42eec76e5ee880546a2fea6b8603f79/src/pages/StreetView.vue#L186



For the game settings (menu,...), you can follow work made it #118

**Comment by BurAndBY** [comment]
I'm not very good at programming, but i found[ this website](https://medium.com/swlh/filtering-sorting-and-searching-in-arrays-with-vue-js-f60951c040fc)
