### ISSUE TITLE
[BUG] Incorrect Firebase URL

### ISSUE THREAD

**Issue by Mavyre** [GeoGuess/Geoguess#139]
**Describe the bug**
Firebase database URL is incorrect, thus not allowing to create new room

**To Reproduce**
1. Create a new firebase database
2. Receive a -default-rtdb.region.firebasedatabase.app
3. Geoguess won't connect to database

**Expected behavior**
Be able to modify the entire address of the firebase db

**Screenshots**
![image](https://user-images.githubusercontent.com/4330449/111052811-b695e080-845e-11eb-9166-60a01d4810f0.png)

**Desktop / Smartphone(please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: 0.5.0

**Additional context**

As a quickfix, I have been able to modify main.js to change the URLs of the database.

**Comment by wlanowski** [comment]
For me it is working. Was there a syntax-error in your .env file or your .env variables?

Do you want to deploy Geoguess via netlify or vercel? Or do want to host geoguess on your own webserver with apache or nginx?

**Comment by Mavyre** [comment]
Hey John,

When creating a firebase database, I didn't get the expected URL ending by .firebase.com as the documentation stated, but a -default-rtdb.region.firebasedatabase.app.

Everything is deployed on Netflify.

**Comment by wlanowski** [comment]
Yes, you are absolutely right. I looked into the firebase SDK, the databaseURL-variable is not present anymore.

You can look at the section "Realtime Database". The URL here is the variable databaseURL that has to be used.

![geoguessscreen](https://user-images.githubusercontent.com/25705332/111054700-d6350500-846e-11eb-884c-3eadf389be3c.jpg)

Can you report, if this works? Thank you very much for reporting this issue!

(@BilelJegham do we have to change the API in Geoguess to work without this variable, or do we have to update our instructions? If we have to update the instructions, I love to assign this issue to me. I have also a plan to write instructions for those, who want to run geoguess on self-hosted web server.)

**Comment by Mavyre** [comment]
@wlanowski Instructions might have to be updated a bit to match the new Firebase's interface (the current one are enough to find out what to do on the new one though).

Also, the main.js variables need a bit of tweaking to work. New firebase RTDB URLs look like: 
[project-id]-default-rtdb.[region].firebasedatabase.app
Currently, the database the app is trying to hit is [project-id].firebaseio.com.

I had to change both authDomain and databaseURL of the main.js to make it work. I confirm everything works fine, just the URL schema of Firebase has changed!

**Comment by BilelJegham** [comment]
It has been update ref #68 . 
Env var "VUE_APP_FIREBASE_DATABASE_URL" and "VUE_APP_FIREBASE_AUTH_DOMAIN" has been added

![image](https://user-images.githubusercontent.com/20130405/111079024-6f5c2e00-84f8-11eb-97c0-d25c07358bdc.png)
Source: https://geoguess.games/guide/instructions.html

**Comment by BilelJegham** [comment]
Hello 
It has been updated ref #68 . 
Env var "VUE_APP_FIREBASE_DATABASE_URL" and "VUE_APP_FIREBASE_AUTH_DOMAIN" has been added

![image](https://user-images.githubusercontent.com/20130405/111079024-6f5c2e00-84f8-11eb-97c0-d25c07358bdc.png)
Source: https://geoguess.games/guide/instructions.html


What other changes did you see on Firebase ? @Mavyre

**Comment by Mavyre** [comment]
@BilelJegham That PR should cover all the issue I had!
