### ISSUE TITLE
[BUG] Record becomes 0 when playing Country Mode

### ISSUE THREAD

**Issue by Mavyre** [GeoGuess/Geoguess#141]
**Describe the bug**
The personal record becomes 0 when playing the Country game mode. The history also displays distance 0.

**To Reproduce**
1. Play a game in country mode
2. Check your personal record

**Expected behavior**
Record should not be updated while playing Country game mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/4330449/111165267-1dbaae80-859f-11eb-8463-48b454174ff9.png)

**Desktop / Smartphone(please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: v0.5.0

**Comment by BilelJegham** [comment]
This is a remains of the 1st version without custom map feature and country mode
We need to find another value. (number of places visited, countries, ....)
Link to Player profile: stats #37
