### ISSUE TITLE
[BUG] Google Maps are negative and "for development purposes only"

### ISSUE THREAD

**Issue by ahulii** [GeoGuess/Geoguess#158]
After 3-4 games solo and 2 games with friends on my country's map that was chose in menu after writing first letters I saw that all maps are negative.
![image](https://user-images.githubusercontent.com/61556142/114768920-29ea8500-9d72-11eb-926a-ff1a44d6996d.png)
Also, maps are alerting that it's for developing purposes only.
![image](https://user-images.githubusercontent.com/61556142/114769024-4e466180-9d72-11eb-9e92-f59fd002a1d5.png)
That didn't happened in the beginning but happened after 6 games. This problem is also on my friends' PC shown. 
Please, fix it or write suspected causes of this problem.
Thank you for your game! It's much better than "we know what"!

**Comment by BilelJegham** [comment]
Hello,
It's linked to "Maps JavaScript API" quotas :

 - If you play on demo.geoguess.games is a demo. GeoGuess was build for SelfHost.
I advise you to consider hosting your GeoGuess. Manual is here: https://geoguess.games/guide/instructions.html

 - If you already self-host, you need to change to daily "Maps JavaScript API" quota (https://geoguess.games/guide/instructions.html#quotas)
