### ISSUE TITLE
[FEAT] Streamer mode

### ISSUE THREAD

**Issue by BurAndBY** [GeoGuess/Geoguess#193]
**Is your feature request related to a problem? Please describe.**
People will streamsnipe me.

**Describe the solution you'd like**
Add censore of names - ex. B****BY

**Describe alternatives you've considered**
Using geoguessr extension for chrome. Works only on PC.

**Comment by BilelJegham** [comment]
GeoGuess have already streamer Mode since PR : #167  for URL and room names

I don't see the need, you can choose a fake name?

**Comment by BurAndBY** [comment]
> GeoGuess have already streamer Mode since PR : #167 for URL and room names
> 
> I don't see the need, you can choose a fake name?

Well... that's an idea too
