### ISSUE TITLE
[FEAT] Random points of your Google location history

### ISSUE THREAD

**Issue by nambrot** [GeoGuess/GeoGuess#211]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
I always wanted a GeoGuessr-like game, but for my own personal location history that I get from Google. It would be a nice test to see how well I remember the places I have been to.

**Describe alternatives you've considered**
If I understand correctly, I can just create GeoJSONs randomly from my location history and then import them as a map?

**Comment by BilelJegham** [comment]
Hello @nambrot 
You are right. 
You should download location history from https://takeout.google.com/ and create a GeoJSON file.

Map documentation is available here : https://geoguess.games/guide/dev/maps.html

**Comment by nambrot** [comment]
Thanks I just tried it out and for anyone interested in doing this, one challenge I found is that I end up with a lot of points of me driving to the middle of nowhere which is not as interesting :)

I forked from https://github.com/Scarygami/location-history-json-converter to [add a geojson output and tried to dedup by rounding the coordinates](https://github.com/nambrot/location-history-json-converter), and it worked ok. I think ideally someone should really process the semantic locations that Google provides instead of the raw locations
