### ISSUE TITLE
[BUG] 'With friends' stoped to work

### ISSUE THREAD

**Issue by Rapt0rTTV** [GeoGuess/Geoguess#216]
when you try to make a room name it never works and wont take you to the next screen..

**Expected behavior**

**Screenshots**

**Desktop / Smartphone(please complete the following information):**
 - OS: [e.g. Windows, iOS]
 - Browser [e.g. chrome, stock browser, safari]

**Additional context**

**Comment by BilelJegham** [comment]
Hello @Rapt0rTTV ,

Can you provide more details, please?
 - screenshot
 - Did you change your firebase configuration?
 - You should have an error in your browser console (F12) when you type the room name, can you provide it?

Best regards,
Bilel

**Comment by BurAndBY** [comment]
> when you try to make a room name it never works and wont take you to the next screen..
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop / Smartphone(please complete the following information):**
> 
> * OS: [e.g. Windows, iOS]
> * Browser [e.g. chrome, stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Seems like you just added multiplayer api or haven't added them at all. If you do then redeploy website using Vercel or Netlify. If you haven't added API using Firebase, do that using this guide https://geoguess.games/guide/instructions.html#_2-2-firebase-multiplayer

Hope it helps,
BurAndBY

**Comment by Rapt0rTTV** [comment]
![image](https://user-images.githubusercontent.com/90581947/133555861-48a339cd-54be-4174-b8e7-3638042eaad0.png)

**Comment by BilelJegham** [comment]
It seems you play on geoguess.tk which does not depends on us;
As you see the owner has disabled the database.
 
 
 You can deploy your server by following guide instructions: https://geoguess.games/guide/ (demo is available here https://demo.geoguess.games/)?

**Comment by BurAndBY** [comment]
> geoguess.tk

https://geoguessr.tk/
