### ISSUE TITLE
[FEAT] Registration 

### ISSUE THREAD

**Issue by BurAndBY** [GeoGuess/GeoGuess#217]
**Is your feature request related to a problem? Please describe.**
Make a registration that save all your scores, player name. NOT A DUPLICATE OF #186

**Describe the solution you'd like**
Make registration that will save all the scores and player name

**Describe alternatives you've considered**
Farming points using GeoGuessr Hacks

**Additional context**
After changing PC my score nulled off

**Comment by BurAndBY** [comment]
I know about GeoSave, hard to find place to host them

**Comment by BilelJegham** [comment]
Hello,
I don't think it's useful. It would use only for history.
It had complexity in configuration. We try to rely less on Firebase. 


You can easily upload GeoSave on Github Gist, Google Drive, Dropbox... :wink: 

Best regards
