### ISSUE TITLE
Can't enter name for multiplayer lobby

### ISSUE THREAD

**Issue by FelixWeichselgartner** [GeoGuess/GeoGuess#447]
**Describe the bug**
Can't enter name for multiplayer lobby. Or "Next" is doing nothing.

**To Reproduce**
Play with friends, enter a name, press next.

**Expected behavior**
should create some kind of lobby

**Desktop / Smartphone(please complete the following information):**
 - OS: Windows11 and Windows10

**Comment by BilelJegham** [comment]
Hello @FelixWeichselgartner,
Could you add a screenshot of your logs in your browser console (F12 on chrome) ?

**Comment by FelixWeichselgartner** [comment]
![grafik](https://user-images.githubusercontent.com/41804639/169668983-5dfc730d-98d8-4a5c-88d1-25489a34548f.png)

**Comment by FelixWeichselgartner** [comment]
Im using Firefox 100.0.2 (64-Bit)

**Comment by BilelJegham** [comment]
You play on  the first version of GeoGuess. Please upgrade your server.
![image](https://user-images.githubusercontent.com/20130405/169669934-c413d1b6-5260-40e6-995a-bcff9374fc4e.png)

Last version demo : https://demo.geoguess.games/

**Comment by FelixWeichselgartner** [comment]
Thanks for the tip! Google showed me this site: https://geoguessr.tk/
I was not aware, that it's not an "official" website.
Have a nice sunday!
