### ISSUE TITLE
Improve homepage : image quality, animation, fonts, colors, etc.

### ISSUE THREAD

**Issue by BilelJegham** [GeoGuess/GeoGuess#53]

**Comment by BilelJegham** [comment]
@simonrousseau  What do you mean with Improve homepage ? Can you, maybe, add  screenshot with detail ? :)

**Comment by wlanowski** [comment]
the silver crown at the Score page at the end of the game is to bright and so nearly unvisible. There should be another color for this.

**Comment by wlanowski** [comment]
> 
> 
> the silver crown at the Score page at the end of the game is to bright and so nearly unvisible. There should be another color for this.

Made PR #94 to fix this

**Comment by simonrousseau** [comment]
👋
