### ISSUE TITLE
Be able to save played maps in order to play again / share them

### ISSUE THREAD

**Issue by BilelJegham** [GeoGuess/Geoguess#54]

**Comment by wlanowski** [comment]
Isn't it already possible in the History? (Close this issue?)

**Comment by BilelJegham** [comment]
I don't take the time to complete the description. 

We would like to :
 - add button "export map" as geojson in the Custom Maps Modal 
 - add cards "lasted maps played" like show in the Figma mock-up https://www.figma.com/file/AhxfXiZ9Y21yqju7LL7Nnc/Geoguess-2
