### ISSUE TITLE
Awesome project ❤️

### ISSUE THREAD

**Issue by arthurfiorette** [GeoGuess/GeoGuess#549]
I'm here just to say thanks for all you guys who built this amazing OSS game. Its been bringing fun for me and my college friends during any boring class this year :).

P.S.: Can you guys set up a github sponsor? I'd donate.

**Comment by BilelJegham** [comment]
Hello, 
It's rewarding to have that kind of feedback

Thank you

GitHub sponsor added on the repo if you want ;)
