### ISSUE TITLE
[BUG] Docker container returns 404 when visiting relative URLs 

### ISSUE THREAD

**Issue by sibbl** [GeoGuess/GeoGuess#619]
**Describe the bug**
When visiting `/room/test` in the Docker container, the nginx does return a 404. 

**To Reproduce**
1. Deploy the Docker container e.g. using the docker-compose.yaml and the image of this repository
2. Create a new room called "test"
3. Open the URL shown in the dialog, e.g. http://localhost:3000/room/test
4. A 404 is returned

**Expected behavior**
The `index.html` is returned, so that Vue router can show the correct view.

**Comment by tigattack** [comment]
I was able to fix this like so:

```diff
# /etc/nginx/conf.d/default.conf
server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

+    root   /usr/share/nginx/html;
+    index  index.html index.htm;

    location / {
-        root   /usr/share/nginx/html;
-        index  index.html index.htm;
+        try_files $uri $uri/ /index.html;
    }
```

**Comment by aadityadhruv** [comment]
Did you make this a permanent change by mounting the file to the path? I'm facing the same issue.

**Comment by aadityadhruv** [comment]
I did precisely that, and it worked. Thanks!
