### ISSUE TITLE
Multiplayer Not Working -- streetView not saved in firebase

### ISSUE THREAD

**Issue by bestbotplease** [GeoGuess/Geoguess#64]
I pulled master following the guide, hosted on netlify + set up firebase real-time DB. Single player works fine.
Whenever I create a multiplayer game, I set the room name, my player name, and the timeout period. Everything is created and I receive a message that says waiting on players to join. I noticed the following error in my javascript console:

`Uncaught Error: Reference.set failed: First argument contains undefined in property 'dsafasdf.streetView.round1.roundInfo'`

Whenever another player attempts to join my URL, they receive the following error:

_The first player is creating the room right now. Please wait and try again._

After looking into the issue, it looks like streetView is never saved in Firebase. Thus, the condition on line 170 in DialogRoom.vue is met:  `!snapshot.hasChild('size') || !snapshot.hasChild('streetView’)`

This is what causes the error to display. I’m not sure why streetView isn’t being saved in Firebase, but that must be the issue. I have not been able to find the code where this happens to further debug. Everything else appears to be working.

**Comment by H0r53** [comment]
It looks like the issue is in `StreetView.vue`. The `loadStreetView` method is called on mount for player1, which is where the random coordinates are generated. Then `checkStreetView` is called, which attempts to save the streetView to Firebase around line 236. I reproduced the issue but don't see a fix yet.

**Comment by BilelJegham** [comment]
Hi, thanks for the report.

I found the problem, linked to maps without round information.

I finish my test and I will merge the fix.

**Comment by bestbotplease** [comment]
Awesome, looks like the bug fix worked. Thanks for the quick help.

**Comment by BilelJegham** [comment]
Sorry for the inconvenience

Enjoy
