### ISSUE TITLE
[FEAT] Support for country streaks

### ISSUE THREAD

**Issue by code-logger** [GeoGuess/GeoGuess#643]
Allow user to play country streak

**Comment by BilelJegham** [comment]
Hello @code-logger, 

It not that simple, pls follow Issues templates ;)

Best regards

**Comment by code-logger** [comment]
gecoding api can be used to get location info which can be used to know if user correctly guessed or not

**Comment by BilelJegham** [comment]
![image](https://user-images.githubusercontent.com/20130405/230956347-2b075509-405f-400a-b80e-2185ff65a816.png)

Did play with Pick Country mode ?
