### ISSUE TITLE
is there a way to save history, the time each round took and distance score, right now when you export the csv it only lists the location lng and lat which isn't useful for educational purposes  

### ISSUE THREAD

**Issue by bwazzan** [GeoGuess/GeoGuess#644]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BilelJegham** [comment]
Hello, have you checked "export  as GeoSave" feature (it's json) ?
![image](https://user-images.githubusercontent.com/20130405/232151675-6dad5626-3a1e-405f-afc6-3b90c056481a.png)


Example
![image](https://user-images.githubusercontent.com/20130405/232151545-27519fbe-dc5a-4223-a08b-2cd69d3cd1ea.png)



Next time can you be more precise by following the Issue Template. 
![image](https://user-images.githubusercontent.com/20130405/232152208-a8f95067-e6eb-4526-9589-89158ab2d7c6.png)

It helps a lot maintainer like me which to understand your need ;)

**Comment by bwazzan** [comment]
Hi bileJegham, thanks for your answer, when creating a custom map with 5 locations the app crashes after the second round is there a reason for that happening? I have an unlimited api key but it still crashes.

**Comment by BilelJegham** [comment]
Hello @bwazzan 
I reproduce the bug..., I will investiguate.

I advice you to use custom map with more points
