### ISSUE TITLE
Unsplash.com images no longer available

### ISSUE THREAD

**Issue by MattsBos** [GeoGuess/GeoGuess#646]
### Describe the bug

Images used for several area tiles sourced from unsplash.com no longer work.

- https://source.unsplash.com/500x230/weekly?Continent
- https://source.unsplash.com/500x230/weekly?France%20Region
- https://source.unsplash.com/500x230/weekly?France%20County
- etc..

Only Tunisia governate still functions.

### To Reproduce

No specific need, fails on every install. Can also be seen on the demo.

### Expected behavior

Expected images to load.

### Describe alternatives you've considered

Would probably be best to include these images with one of the project repo's instead of 3rd party locations.

### Screenshots

See `demo.geoguess.games`

### What is your OS ?

Windows

### What browsers are you seeing the problem on?

Microsoft Edge

### Version

latest geoguess:master image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilelJegham** [comment]
When imageUrl is not set in the catalogue of https://github.com/GeoGuess/GeoGuess-Maps, GeoGuess will generate an image with Source API unsplash.

But Source API from unsplash.com was deprecated (https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html) and today down ...


I add imageUrl in https://github.com/GeoGuess/GeoGuess-Maps/pull/39

Thanks for report
