### ISSUE TITLE
Problem with GEOJson custom map

### ISSUE THREAD

**Issue by chalbin73** [GeoGuess/Geoguess#67]
Hello,
I came accros a little problem while playing your game. I wanted to play in my own city, so I created a custom GEOJson with polygon around my city. I launched the game and i had this messages "Nearby Position : Unfortunately, we were unable to find a random position in the defined location. However, we have found one nearby 😉". I'm sure that the StreetView car went through my city : i tested with waypoints it worked.

Thank you very much !
Albin

**Comment by BilelJegham** [comment]
Hi,
It's link to small city with large not "street view" area. 
The algorithm pick an random position in polygon and find the closest place streetviewed. If the place aren't in the polygon, it repeat the operation. Maximum 3 times, else it print the message "Nearby Position".

An example, a village (5.16 m²) near a river. The position pick is generally on the other side of the river.
![image](https://user-images.githubusercontent.com/20130405/100669070-1f989300-335d-11eb-913b-92e0484209ac.png)
Google Map link : https://goo.gl/maps/mbUmUefmdLQMrNrF9

Does it's criteria match with your city?

I advise you to make your maps with point and not polygon 😉. In the future, we should take the time to change the algorithm.

**Comment by chalbin73** [comment]
Hi,
I don't think that this is the case. I made a little test :
First, i selected a small area with only roads in it and I made sure that there is a lot of other roads around the polygon (of course all the roads are streetviewed) :
![MAP1](https://user-images.githubusercontent.com/59101580/100774753-b703f180-3402-11eb-91bd-93ecac118740.PNG)
This is the area that i selected (not a lot of empty spaces in the polygon and some roads arround)
![MAP2](https://user-images.githubusercontent.com/59101580/100774950-ee729e00-3402-11eb-96c0-b4dd06604983.PNG)
And this is the place where I spawn on all rounds (I marked it with a waypoint)
There is a lot of roads beetween the polygon and the waypoint.
Google map : [https://goo.gl/maps/CUvaHp2Wkoc65QQ19](url)
And the GEOJson that I used : [http://pastebin.fr/75928](url) (The point in it is the place where I spawn at each rounds)

Thank you for your fast answer !

**Comment by BilelJegham** [comment]
Sorry for the delay, 

I thinks I know where is the problem.

We define the panorama search with a radius of 100km. 😅

I will test to change this week.
https://github.com/GeoGuess/Geoguess/blob/68ccad6d183a558d43394321e88a0759a27bb7b0/src/pages/StreetView.vue#L165

**Comment by BilelJegham** [comment]
It's finally fix 😃 

Can you check it's good for you on  : https://deploy-preview-69--geoguess2.netlify.app/

Thank you in advance.

@all-contributors please add @chalbin73 for bug
