### ISSUE TITLE
Firebase url env

### ISSUE THREAD

**Issue by AlexSpelt** [GeoGuess/Geoguess#68]
Google Firebase has an option to use a server in west Europe for me. But I think the firebase URL changes because of that option. 

Right now Geoguess uses https://<firebase project id>.firebaseio.com. I had to use https://<firebase project id>-default-rtdb.europe-west1.firebasedatabase.app.

I solved this issue by changing the code from my forked version in src/main.js.

I suggest adding a separate env variable for URLs.

**Comment by BilelJegham** [comment]
Thanks for the report, 

I didn't know.

I had 3 times, pull request merged soon :)

**Comment by BilelJegham** [comment]
Thanks for the report. I didn't know.

I had 3 env variables : VUE_APP_FIREBASE_AUTH_DOMAIN, VUE_APP_FIREBASE_DATABASE_URL, VUE_APP_STORAGE_BUCKET

The pull request will merge soon :) Thanks for the report. I didn't know.

I had 3 env variables : VUE_APP_FIREBASE_AUTH_DOMAIN, VUE_APP_FIREBASE_DATABASE_URL, VUE_APP_STORAGE_BUCKET

The pull request will merge soon :)

**Comment by BilelJegham** [comment]
@all-contributors please add @AlexSpelt for bug
