### ISSUE TITLE
[BUG]: inverted colors and google maps error.

### ISSUE THREAD

**Issue by derspyy** [GeoGuess/GeoGuess#721]
### Describe the bug

![image](https://github.com/GeoGuess/GeoGuess/assets/65043391/d20a3b89-101b-44b1-a081-b687975e0a0e)
we playin evil geoguessr fr 😈

### To Reproduce

i just started a new game.

### Expected behavior

unsilly. please.

### What is your OS ?

Windows, Linux

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Version

the demo on the website. 1.0.0 afaik.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElectricS01** [comment]
This is not a bug, remember to check the faq in the Official Discord server, here's what it says:
<img width="1037" alt="image" src="https://github.com/GeoGuess/GeoGuess/assets/103579308/c35a8c18-16cc-4002-826e-8ead303410e7">

**Comment by derspyy** [comment]
oh cool, thanks :)
