### ISSUE TITLE
[FEAT]: Seed for simple multiplayer

### ISSUE THREAD

**Issue by Kvan7** [GeoGuess/GeoGuess#728]
### Is your feature request related to a problem? Please describe.

I want to be able to play with my friends quickly without setting up firebase. Since I am doing this in the same room as them usually, I don't need to be in the same like lobby but just so we can get the same map gen.

### Describe the solution you'd like

Just like a minecraft like seed for the random, i can mostly leave it blank and it just works but when with friends we can set it to something and get the same map to play against. Could also be nice to share a seed if I find something cool or weird so others can see it too.

### Describe alternatives you've considered

I guess i could go and figure out firebase, I just don't really want to have to pay for stuff like that. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilelJegham** [comment]
Hello, you can use Share functionality to share a previous game.

Go to History page and click on share icon 

![share](https://github.com/GeoGuess/GeoGuess/assets/20130405/9314c698-d7b3-4ae9-aeb4-18d87d87db41)
