### ISSUE TITLE
GeoGuess Demo on outdated build

### ISSUE THREAD

**Issue by ElectricS01** [GeoGuess/GeoGuess#750]
### Describe the bug

https://demo.geoguess.games/ is using an older version of geoguess that doesn't support light/dark themes etc.

### To Reproduce

Go to https://demo.geoguess.games/

### Expected behavior

It's out of date

### What is your OS ?

MAC

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Version

1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilelJegham** [comment]
Hello,
v1.0.0 not include dark mode, I will create new version

**Comment by BilelJegham** [comment]
v1.1.0 released
