### ISSUE TITLE
[BUG]: maps.json is missing

### ISSUE THREAD

**Issue by daemon-byte** [GeoGuess/GeoGuess#809]
### Describe the bug

The url https://maps.geoguess.games/maps.json throws a 404 and that stops it from loading all the premade maps on the homepage.

### To Reproduce

Open the homepage. Including the demo site https://demo.geoguess.games

### Expected behavior

You see a list of premade maps to pick from

### What is your OS ?

Linux

### What browsers are you seeing the problem on?

Chrome

### Version

master

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BilelJegham** [comment]
Fix, didn't understand why Github remove the custom domain configuration for the maps repository (https://github.com/GeoGuess/GeoGuess-Maps/settings/pages)

Thx for the report.

**Comment by DerEchteJoghurt** [comment]
This seems to be broken again. https://maps.geoguess.games/maps.json results in a 404.

**Comment by BilelJegham** [comment]
Fixed
Love Github 😔 , which remove custom domain configuration

**Comment by BilelJegham** [comment]
Thx @DerEchteJoghurt for the report
