### ISSUE TITLE
Button on Starting Page to Enter room

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#90]
I installed a geoguess-server on my virtual server. On my Tablet I Installed this Geoguess-Instance as progressive Webapp via Firefox (like [here](https://www.reddit.com/r/firefox/comments/i4gzxe/what_does_the_install_button_trigger_on_firefox/?utm_medium=android_app&utm_source=share)). This is very nice! In this way, Geoguess is good playable with mobile Devices like Android Tablets.

Unfortunately I am not able to enter URLs via this progressive Web App, so joining a room, by enter the URL is not possible. There should be a third Button on the starting page, called "Join existing room". To implement progressive Web apps should be very easy then! :)

**Comment by BilelJegham** [comment]
You can join a room name already with the Multiplayer button ?


![image](https://user-images.githubusercontent.com/20130405/106049162-21c16880-60e6-11eb-8f81-f3c37150122d.png)


GeoGuess PWA is displayed in Standalone Mode which hides the address bar of the browser.
https://github.com/GeoGuess/Geoguess/blob/06c4ed49237342ccc9a4868fd816a8db292b5499/public/manifest.json#L70

**Comment by wlanowski** [comment]
Ah! I did not notice this, my friends neither. We should change "Type a room name" to e.g. "Type a room name to create a new room or join a existing room". We thought this button is to create a room only.

**Comment by wlanowski** [comment]
> 
> 
> Ah! I did not notice this, my friends neither. We should change "Type a room name" to e.g. "Type a room name to create a new room or join a existing room".

So can we do this? :)

**Comment by BilelJegham** [comment]
Change in #102. For future label issue don't hesitate to change en.json in PR :)
