### ISSUE TITLE
.env.dist not complete

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#92]
If you want to build Geoguess on your own instance with nodejs/npm you need more information as given in .env(.dist). Otherwise firebase is not able to connect.

I had to add the vars VUE_APP_FIREBASE_AUTH_DOMAIN, VUE_APP_FIREBASE_DATABASE_URL, VUE_APP_STORAGE_BUCKET on my own to .env before building.

**Comment by BilelJegham** [comment]
Yes, change the documentation we change the documentation and forgot the `.env.dist`

Can you make a PR ?

**Comment by wlanowski** [comment]
PR done.
