### ISSUE TITLE
"Are you sure to leave this window?" should be implemented?

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#95]
Hi there!

It is a big problem, especially on mobile devices, that reloading the page, or "going back" in the browser destroys the game for all players. Maybe it is possible to implement this "Are you sure to leave this page" allert via JS as a first step. (Would be this okay with PWA requirements? Idk). Maybe later it would be nice, if it is possible to reenter to the room and leaving without destroying the game.

**Comment by BilelJegham** [comment]
I answer in discord. I don't see PR to that yet. 😢

Ask him maybe he will make a PR.

https://discord.com/channels/758443244387303435/758976664050335764/796800342717235201

**Comment by BilelJegham** [comment]
> Maybe later it would be nice, if it is possible to reenter to the room and leaving without destroying the game.

For this, maybe one day. I now how it can be frustrating

**Comment by wlanowski** [comment]
I want to highlight this issue because it is a big problem within my playing community...

It would be nice if this alert appears. We should prove whether this alert is compatible with PWA, we should not destroy our PWA-functionality with this...

**Comment by BilelJegham** [comment]
Did you ask on discord FunnyPocketBook to make an pr ?https://discord.com/channels/758443244387303435/758976664050335764/796800342717235201

**Comment by BilelJegham** [comment]
Did you ask on discord FunnyPocketBook to make an pr ? @wlanowski https://discord.com/channels/758443244387303435/758976664050335764/796800342717235201

**Comment by BilelJegham** [comment]
@wlanowski Made, can you check on  https://deploy-preview-107--geoguess2.netlify.app/ ?
😉

**Comment by wlanowski** [comment]
Looks good! Checked on desktop, mobile (firefox and chrome) and pwa (firefox and chrome).

If possible, add the possibility to translate "Are you sure to leave the current game" via crowdin.

Thanks a lot!
