### ISSUE TITLE
Bug: Player should create room, although room has already been created 

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#96]
I don't know, how I can reproduce this bug, but sometimes it is not possible to join existing rooms. The new player, which want's to join a room (via URL), gets the dialog to create a new room. After creating a new room with a other name, there is no problem to join.

I will have a eye on this, to reproduce this, or find the reason for this. (Developer Console, Firebase, ...)

**Comment by BilelJegham** [comment]
I think it's linked to the round initialization.
 Until the random position hasn't set-up for the first player, the room isn't "Ready to join".

Is it a custom map game?

**Comment by wlanowski** [comment]
No, it was a normal map. I am not able to reproduce this yet :( It comes randomly for me.
I will give you more information, asap.
