### ISSUE TITLE
"Play again" at end of a game doesn't play custom map again

### ISSUE THREAD

**Issue by wlanowski** [GeoGuess/Geoguess#99]
"Play again" at end of a game doesn't play a custom map again. It is always starting standard world map. It should start the chosen custom map again.

**Comment by Mavyre** [comment]
I can add that it looses all the game properties (custom map, timing, ...). Seems that we need to pass all property when re-playing.

**Comment by BilelJegham** [comment]
Yes, the button was just a link to "/streetview".

 With the pull request of @viniciusdof #138, I think we can make it.
